import * as THREE from './vendor/three.module.js';
import {PixelRenderer} from './engine/pixel-renderer.js';
import {createPixelActor} from './engine/pixel-actor.js';
import {PixelWorld} from './engine/world.js';
import {building} from './content/building.js';

document.head.insertAdjacentHTML('beforeend','<style>header a,header #status{padding:11px 13px!important;border:2px solid #dff9ff!important;background:#061017f5!important;color:#fff!important;text-shadow:0 1px 2px #000!important}header small{font-size:11px!important;color:#c8f4ff!important;text-shadow:0 1px 2px #000!important}h1{font-size:clamp(25px,4vw,40px)!important;text-shadow:0 2px 3px #000!important}#status{font-size:11px!important;color:#d5ffe6!important}#room{display:none!important}#prompt{padding:12px 18px!important;border:2px solid #8be6ff!important;background:#061017f5!important;color:#fff!important;text-shadow:0 1px 2px #000!important;font-size:13px!important}#dialogue{background:#061017f5!important}#dialogue b{font-size:14px!important;color:#d4f8ff!important}#dialogue .world-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}</style>');

const canvas=document.querySelector('#stage'),status=document.querySelector('#status'),roomLabel=document.querySelector('#room'),prompt=document.querySelector('#prompt'),dialogue=document.querySelector('#dialogue');
const display=new PixelRenderer(THREE,canvas),world=new PixelWorld(THREE,display.scene,building),hero=createPixelActor(THREE),clock=new THREE.Clock(),keys={},touch={forward:false,back:false,left:false,right:false};
canvas.tabIndex=0;canvas.focus({preventScroll:true});
display.scene.add(hero.group);hero.group.position.set(building.spawn.x,0,building.spawn.z);let nearby=null,lastA=false;
let soundContext,roomTone,roomGain,roomPan;
function enableRoomSound(){if(soundContext)return;const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;soundContext=new Audio();roomTone=soundContext.createOscillator();roomGain=soundContext.createGain();roomPan=soundContext.createStereoPanner?.();roomTone.type='triangle';roomTone.frequency.value=73;roomGain.gain.value=.0001;if(roomPan){roomTone.connect(roomGain).connect(roomPan).connect(soundContext.destination)}else roomTone.connect(roomGain).connect(soundContext.destination);roomTone.start();soundContext.resume?.()}

function openRoute(route){if(parent!==window&&parent.openPanel)parent.openPanel(route);else location.href=route}
function showStation(title,copy,actions=[]){dialogue.replaceChildren();const heading=document.createElement('b'),text=document.createElement('p'),buttons=document.createElement('div');heading.textContent=title;text.textContent=copy;buttons.className='world-actions';actions.forEach(([label,action])=>{const button=document.createElement('button');button.textContent=label;button.onclick=action;buttons.append(button)});dialogue.append(heading,text,buttons);dialogue.hidden=false}
function interact(){if(!nearby)return;if(nearby.game){showStation(nearby.name,'This cabinet is ready. Open Pocket Archive only when you want to leave the building and play it.',[['Play game',()=>{try{sessionStorage.setItem('novashell-world-game',nearby.game.rom||nearby.game.name||'')}catch{}openRoute('/pages/arcade.html')}],['Stay here',()=>dialogue.hidden=true]]);return}if(nearby.action==='orbit'){showStation('RADIO ORBIT','The speaker is part of this room. The full radio window is optional, so walking up to it never interrupts the world.',[['Open full Orbit',()=>parent.openOrbit?.()],['Stay in World',()=>dialogue.hidden=true]]);return}if(nearby.action==='relay'){showStation('RELAY','Relay is available from the workstation. Open it only when you want the full assistant window.',[['Open Relay',()=>parent.openAssistant?.()],['Stay in World',()=>dialogue.hidden=true]]);return}if(nearby.route)showStation(nearby.name,'This station is connected and ready. Open its full NovaShell surface when you choose.',[[`Open ${nearby.name}`,()=>openRoute(nearby.route)],['Stay in World',()=>dialogue.hidden=true]])}
dialogue.addEventListener('click',event=>{if(event.target===dialogue)dialogue.hidden=true});
addEventListener('keydown',event=>{if(['Space','Enter','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(event.code))enableRoomSound();keys[event.code]=true;keys[event.key]=true;if(['Space','Enter'].includes(event.code)){event.preventDefault();interact()}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(event.code))event.preventDefault()});addEventListener('keyup',event=>{keys[event.code]=false;keys[event.key]=false});
document.querySelectorAll('[data-move]').forEach(button=>{const direction=button.dataset.move,stop=()=>touch[direction]=false;button.onpointerdown=event=>{enableRoomSound();event.preventDefault();button.setPointerCapture?.(event.pointerId);touch[direction]=true};button.onpointerup=button.onpointercancel=button.onpointerleave=stop});document.querySelector('[data-action]').onclick=()=>{enableRoomSound();interact()};

function input(dt,time){
  const pad=[...(navigator.getGamepads?.()||[])].find(Boolean),dead=value=>Math.abs(value)>.18?value:0;
  let vx=(keys.KeyD||keys.d||keys.ArrowRight||touch.right?1:0)-(keys.KeyA||keys.a||keys.ArrowLeft||touch.left?1:0)+dead(pad?.axes?.[0]||0),vz=(keys.KeyS||keys.s||keys.ArrowDown||touch.back?1:0)-(keys.KeyW||keys.w||keys.ArrowUp||touch.forward?1:0)+dead(pad?.axes?.[1]||0);
  const length=Math.hypot(vx,vz),moving=length>.08;if(moving){vx/=Math.max(1,length);vz/=Math.max(1,length);const speed=(keys.ShiftLeft||pad?.buttons?.[1]?.pressed?8:5.7)*dt,position=world.resolve(hero.group.position.x+vx*speed,hero.group.position.z+vz*speed,.52);hero.group.position.x=position.x;hero.group.position.z=position.z}
  const pressed=!!pad?.buttons?.[0]?.pressed;if(pressed&&!lastA)interact();lastA=pressed;hero.update(vx,vz,moving,time);
}
function frame(timeMs){requestAnimationFrame(frame);const dt=Math.min(.05,clock.getDelta()),time=timeMs*.001;input(dt,time);display.follow(hero.group.position,dt);nearby=world.nearest(hero.group.position.x,hero.group.position.z);prompt.hidden=!nearby;if(nearby)prompt.querySelector('span').textContent=' OPEN '+nearby.name;status.textContent=nearby?'NEAR '+nearby.name:'WASD / ARROWS · EXPLORE';const orbit=world.stations.find(station=>station.action==='orbit');if(roomGain&&orbit){const distance=Math.hypot(hero.group.position.x-orbit.x,hero.group.position.z-orbit.z),level=Math.max(0,1-distance/24);roomGain.gain.setTargetAtTime(.002+level*.023,soundContext.currentTime,.08);roomTone.frequency.setTargetAtTime(68+level*20,soundContext.currentTime,.08);if(roomPan)roomPan.pan.setTargetAtTime(Math.max(-.85,Math.min(.85,(orbit.x-hero.group.position.x)/16)),soundContext.currentTime,.08)}for(const station of world.stations){if(station.pad)station.pad.material.emissiveIntensity=(nearby?.id===station.id)?0.75:0.18}display.draw()}

fetch('/api/games').then(response=>response.json()).then(data=>{(data.games||[]).slice(0,8).forEach((game,index)=>world.addArcade(game,index));status.textContent=(data.games||[]).length+' LOCAL CABINETS READY'}).catch(()=>status.textContent='BUILDING READY');
window.NovaShellWorld={position:()=>({x:Number(hero.group.position.x.toFixed(2)),z:Number(hero.group.position.z.toFixed(2))})};
requestAnimationFrame(frame);
