import * as THREE from './vendor/three.module.js';

const canvas=document.querySelector('#stage'),status=document.querySelector('#status'),prompt=document.querySelector('#prompt'),dialogue=document.querySelector('#dialogue');
const renderer=new THREE.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(1);renderer.setClearColor(0x071017);renderer.shadowMap.enabled=false;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(48,1,.1,120),clock=new THREE.Clock(),hero=new THREE.Group(),keys={},touch={forward:false,back:false,left:false,right:false},stations=[];let nearby=null,lastOpen=false;
scene.fog=new THREE.Fog(0x1a2940,22,62);scene.add(new THREE.HemisphereLight(0x9ec9ff,0x253620,2));const sun=new THREE.DirectionalLight(0xffe5ae,1.6);sun.position.set(-10,16,8);scene.add(sun);
function mat(color,emissive=0){return new THREE.MeshLambertMaterial({color,emissive,emissiveIntensity:1});}function box(w,h,d,color,x=0,y=h/2,z=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);scene.add(m);return m}function label(text,color){const c=document.createElement('canvas');c.width=256;c.height=64;const x=c.getContext('2d');x.fillStyle='#061017';x.fillRect(0,0,256,64);x.strokeStyle=color;x.lineWidth=4;x.strokeRect(2,2,252,60);x.fillStyle='#fff';x.font='bold 22px monospace';x.textAlign='center';x.fillText(text,128,40);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true}));s.scale.set(5,1.25,1);return s}
function floor(){const c=document.createElement('canvas');c.width=c.height=32;const x=c.getContext('2d');x.fillStyle='#263d48';x.fillRect(0,0,32,32);x.strokeStyle='#38525d';x.lineWidth=1;for(let i=0;i<32;i+=8){x.beginPath();x.moveTo(i,0);x.lineTo(i,32);x.moveTo(0,i);x.lineTo(32,i);x.stroke()}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(20,20);t.magFilter=t.minFilter=THREE.NearestFilter;const m=new THREE.Mesh(new THREE.PlaneGeometry(58,48),new THREE.MeshLambertMaterial({map:t}));m.rotation.x=-Math.PI/2;scene.add(m)}
function register(id,name,x,z,action,build){const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);build(g);const tag=label(name,'#73e5ff');tag.position.set(0,5,0);g.add(tag);stations.push({id,name,x,z,action,g});}
function cabinet(g,color){const body=new THREE.Mesh(new THREE.BoxGeometry(3.2,4.8,2),mat('#101820'));body.position.y=2.4;g.add(body);const screen=new THREE.Mesh(new THREE.BoxGeometry(2.55,1.6,.08),mat(color,0.5));screen.position.set(0,3.35,1.04);g.add(screen);const deck=new THREE.Mesh(new THREE.BoxGeometry(2.8,.35,1.1),mat('#25313c'));deck.position.set(0,2.25,1.12);g.add(deck);const coin=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,.08,8),mat('#f6cc62',.2));coin.rotation.x=Math.PI/2;coin.position.set(.9,1.4,1.05);g.add(coin)}
function computer(g){g.add(new THREE.Mesh(new THREE.BoxGeometry(4.1,.5,2),mat('#8b6a46'))).position.y=1.8;const monitor=new THREE.Mesh(new THREE.BoxGeometry(2.6,2,.25),mat('#172634'));monitor.position.set(0,3.25,0);g.add(monitor);const screen=new THREE.Mesh(new THREE.BoxGeometry(2.25,1.55,.06),mat('#65d5bf',.6));screen.position.z=.16;screen.position.y=3.25;g.add(screen);const base=new THREE.Mesh(new THREE.BoxGeometry(.8,.25,.8),mat('#1a222c'));base.position.y=2.1;g.add(base)}
function speaker(g){for(const x of[-1.15,1.15]){const s=new THREE.Mesh(new THREE.BoxGeometry(1.7,3.7,1.3),mat('#14212c'));s.position.set(x,1.85,0);g.add(s);for(const y of[1.2,2.5]){const cone=new THREE.Mesh(new THREE.CylinderGeometry(.45,.45,.12,16),mat('#71cfff',.7));cone.rotation.x=Math.PI/2;cone.position.set(x,y,.71);g.add(cone)}}const turn=new THREE.Mesh(new THREE.CylinderGeometry(1.1,1.1,.28,24),mat('#d1e8ee'));turn.position.set(0,1.2,.1);g.add(turn);const disc=new THREE.Mesh(new THREE.CylinderGeometry(.76,.76,.08,24),mat('#183454'));disc.position.set(0,1.39,.1);g.add(disc)}
function relay(g){const body=new THREE.Mesh(new THREE.BoxGeometry(1.1,2.6,.9),mat('#b967d6',.35));body.position.y=2.1;g.add(body);const head=new THREE.Mesh(new THREE.BoxGeometry(1.45,1.15,1.05),mat('#d58ce8',.3));head.position.y=3.85;g.add(head);for(const x of[-.35,.35]){const eye=new THREE.Mesh(new THREE.BoxGeometry(.18,.18,.08),mat('#d8fbff',1));eye.position.set(x,3.96,.57);g.add(eye)}const halo=new THREE.Mesh(new THREE.TorusGeometry(1.35,.08,6,20),mat('#a9edff',.7));halo.rotation.x=Math.PI/2;halo.position.y=4.6;g.add(halo)}
floor();box(58,1,1,'#152331',0,.5,-23);box(58,1,1,'#152331',0,.5,23);box(1,1,48,'#152331',-29,.5,0);box(1,1,48,'#152331',29,.5,0);
register('arcade','POCKET ARCHIVE',-16,-11,()=>openRoute('/pages/arcade.html'),g=>{cabinet(g,'#f18c62');cabinet(g,'#65b9f1');g.children.forEach((x,i)=>{if(i>3)x.position.x+=3.8})});
register('files','MY LIBRARY',15,-11,()=>openRoute('/pages/files.html?path=My%20Library'),g=>{const cabinet=new THREE.Mesh(new THREE.BoxGeometry(4,3,1.8),mat('#9e714b'));cabinet.position.y=1.5;g.add(cabinet);const handle=new THREE.Mesh(new THREE.BoxGeometry(1.4,.25,.1),mat('#f5d376'));handle.position.set(0,1.5,.96);g.add(handle)});
register('system','SYSTEM DESK',-17,10,()=>parent.document.querySelector('.metric')?.click(),computer);
register('orbit','ORBIT SOUND',0,2,()=>parent.openOrbit?.(),speaker);
register('relay','RELAY',9,10,()=>{dialogue.hidden=false;dialogue.querySelector('p').textContent='You found me. I can explain this machine, open the assistant, or help build a modular local app. Same configured Relay connection—no second key.'},relay);
register('settings','SETTINGS',20,10,()=>openRoute('/pages/settings.html'),g=>computer(g));
hero.add(new THREE.Mesh(new THREE.BoxGeometry(.8,1.4,.7),mat('#e4f5fa')));hero.children[0].position.y=1.1;const head=new THREE.Mesh(new THREE.BoxGeometry(.95,.85,.8),mat('#67bddd'));head.position.y=2.25;hero.add(head);hero.position.set(0,0,14);scene.add(hero);
function openRoute(route){if(parent!==window&&parent.openPanel)parent.openPanel(route);else location.href=route}function interact(){if(!nearby)return;nearby.action();}
dialogue.querySelector('button').onclick=()=>{dialogue.hidden=true;parent.openAssistant?.()};dialogue.addEventListener('click',e=>{if(e.target===dialogue)dialogue.hidden=true});
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','Enter'].includes(e.code)){e.preventDefault();interact()}});addEventListener('keyup',e=>keys[e.code]=false);document.querySelectorAll('[data-move]').forEach(b=>{const k=b.dataset.move;b.onpointerdown=()=>touch[k]=true;b.onpointerup=b.onpointerleave=()=>touch[k]=false});document.querySelector('[data-action]').onclick=interact;
function updateInput(dt){const f=(keys.KeyW||keys.ArrowUp||touch.forward?1:0)-(keys.KeyS||keys.ArrowDown||touch.back?1:0),s=(keys.KeyD||keys.ArrowRight||touch.right?1:0)-(keys.KeyA||keys.ArrowLeft||touch.left?1:0);const pad=[...(navigator.getGamepads?.()||[])].find(Boolean);const px=pad?.axes?.[0]||0,pz=-(pad?.axes?.[1]||0);const vx=s+px,vz=f+pz;if(Math.hypot(vx,vz)>.12){const speed=dt*7;hero.position.x+=vx*speed;hero.position.z-=vz*speed;hero.rotation.y=Math.atan2(vx,-vz)}hero.position.x=THREE.MathUtils.clamp(hero.position.x,-26,26);hero.position.z=THREE.MathUtils.clamp(hero.position.z,-20,20);if(pad?.buttons?.[0]?.pressed&&!lastOpen)interact();lastOpen=!!pad?.buttons?.[0]?.pressed}
function frame(){requestAnimationFrame(frame);const dt=Math.min(.05,clock.getDelta());updateInput(dt);camera.position.lerp(new THREE.Vector3(hero.position.x,14,hero.position.z+15),1-Math.exp(-dt*4));camera.lookAt(hero.position.x,1.8,hero.position.z-4);nearby=stations.map(s=>({...s,d:Math.hypot(hero.position.x-s.x,hero.position.z-s.z)})).filter(s=>s.d<5).sort((a,b)=>a.d-b.d)[0]||null;prompt.hidden=!nearby;if(nearby)prompt.querySelector('span').textContent=' OPEN '+nearby.name;status.textContent=nearby?'NEAR '+nearby.name:'WALK THE DECK';stations.forEach(s=>{if(s.id==='orbit')s.g.rotation.y+=dt*.25;if(s.id==='relay')s.g.children.at(-1).rotation.z+=dt});renderer.render(scene,camera)}
fetch('/api/games').then(r=>r.json()).then(data=>{const games=data.games||[];status.textContent=games.length?games.length+' LOCAL GAMES READY':'LOCAL WORLD READY'}).catch(()=>status.textContent='LOCAL WORLD READY');frame();
