import * as THREE from './vendor/three.module.js';
import {PixelRenderer} from './engine/pixel-renderer.js';
import {createPixelActor} from './engine/pixel-actor.js';
import {PixelWorld} from './engine/world.js';
import {building} from './content/building.js';

document.head.insertAdjacentHTML('beforeend','<style>#dialogue{background:#061017f5!important;color:#fff!important}#dialogue b{font-size:14px!important;color:#d4f8ff!important}#dialogue p{color:#fff!important}#dialogue .world-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}html[data-theme="ultra-retro"] #dialogue{background:#d4d4d4!important;color:#111!important}html[data-theme="ultra-retro"] #dialogue b{color:#000080!important}html[data-theme="ultra-retro"] #dialogue p{color:#111!important}</style>');

const canvas=document.querySelector('#stage'),dialogue=document.querySelector('#dialogue'),controls=document.querySelector('#controls');
let savedSetup={};try{savedSetup=JSON.parse(localStorage.getItem('novashell-world-setup-v1')||'{}')}catch{};if(savedSetup.roomColors)building.rooms.forEach(room=>{if(savedSetup.roomColors[room.name])room.floor=savedSetup.roomColors[room.name]});
const display=new PixelRenderer(THREE,canvas),world=new PixelWorld(THREE,display.scene,building),hero=createPixelActor(THREE),clock=new THREE.Clock(),keys={},touch={forward:false,back:false,left:false,right:false};
canvas.tabIndex=0;const focusWorld=()=>canvas.focus({preventScroll:true});focusWorld();canvas.addEventListener('pointerdown',focusWorld);addEventListener('focus',focusWorld);document.addEventListener('visibilitychange',()=>{if(!document.hidden)focusWorld()});
display.scene.add(hero.group);hero.group.position.set(building.spawn.x,0,building.spawn.z);let nearby=null,lastA=false,lastB=false;
let soundContext,roomTone,roomGain,roomPan;
function enableRoomSound(){if(soundContext)return;const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;soundContext=new Audio();roomTone=soundContext.createOscillator();roomGain=soundContext.createGain();roomPan=soundContext.createStereoPanner?.();roomTone.type='triangle';roomTone.frequency.value=73;roomGain.gain.value=.0001;if(roomPan){roomTone.connect(roomGain).connect(roomPan).connect(soundContext.destination)}else roomTone.connect(roomGain).connect(soundContext.destination);roomTone.start();soundContext.resume?.()}

function openRoute(route){if(parent!==window&&parent.openPanel)parent.openPanel(route);else location.href=route}
function openHomebaseTool(method,fallback){if(parent!==window&&typeof parent[method]==='function'){parent[method]();return}openRoute(fallback)}
function showStation(title,copy,actions=[]){dialogue.replaceChildren();const heading=document.createElement('b'),text=document.createElement('p'),buttons=document.createElement('div');heading.textContent=title;text.textContent=copy;buttons.className='world-actions';actions.forEach(([label,action])=>{const button=document.createElement('button');button.textContent=label;button.onclick=action;buttons.append(button)});dialogue.append(heading,text,buttons);dialogue.hidden=false}
function interact(){if(!nearby)return;if(nearby.game){showStation(nearby.name,'This cabinet is a real entry point for the selected owned game. Play it when you are ready; the building stays open until you choose to leave it.',[['Play game',()=>{try{sessionStorage.setItem('novashell-world-game',nearby.game.rom||nearby.game.name||'')}catch{}openRoute('/pages/arcade.html')}],['Keep exploring',()=>dialogue.hidden=true]]);return}if(nearby.action==='orbit'){showStation('RADIO ORBIT','Use the room speaker as a real optional connection to Orbit. It never opens itself just because you walked past it.',[['Open Orbit',()=>openHomebaseTool('openOrbit','/modules/radio-orbit/index.html')],['Keep exploring',()=>dialogue.hidden=true]]);return}if(nearby.action==='relay'){showStation('RELAY','The workstation is a real optional connection to Relay. It stays out of the way until you choose it.',[['Open Relay',()=>openHomebaseTool('openAssistant','/pages/console.html')],['Keep exploring',()=>dialogue.hidden=true]]);return}if(nearby.route)showStation(nearby.name,'This station connects to its real NovaShell tool only when you choose to open it.',[[`Open ${nearby.name}`,()=>openRoute(nearby.route)],['Keep exploring',()=>dialogue.hidden=true]])}
dialogue.addEventListener('click',event=>{if(event.target===dialogue)dialogue.hidden=true});
addEventListener('keydown',event=>{if(['Space','Enter','Escape','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(event.code))enableRoomSound();keys[event.code]=true;keys[event.key]=true;if(['Space','Enter'].includes(event.code)){event.preventDefault();interact()}if(event.code==='Escape'){event.preventDefault();dialogue.hidden=true}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(event.code))event.preventDefault()});addEventListener('keyup',event=>{keys[event.code]=false;keys[event.key]=false});
document.querySelectorAll('[data-move]').forEach(button=>{const direction=button.dataset.move,stop=()=>touch[direction]=false;button.onpointerdown=event=>{enableRoomSound();event.preventDefault();button.setPointerCapture?.(event.pointerId);touch[direction]=true};button.onpointerup=button.onpointercancel=button.onpointerleave=stop});document.querySelector('[data-action]').onclick=()=>{enableRoomSound();interact()};

function input(dt,time){
  const pad=[...(navigator.getGamepads?.()||[])].find(Boolean),dead=value=>Math.abs(value)>.18?value:0;
  if(controls)controls.textContent=pad?'LEFT STICK · MOVE   A · USE   B · CLOSE':'WASD / ARROWS · MOVE   SPACE / ENTER · USE';
  let vx=(keys.KeyD||keys.d||keys.ArrowRight||touch.right?1:0)-(keys.KeyA||keys.a||keys.ArrowLeft||touch.left?1:0)+dead(pad?.axes?.[0]||0),vz=(keys.KeyS||keys.s||keys.ArrowDown||touch.back?1:0)-(keys.KeyW||keys.w||keys.ArrowUp||touch.forward?1:0)+dead(pad?.axes?.[1]||0);
  const length=Math.hypot(vx,vz),moving=length>.08;if(moving){vx/=Math.max(1,length);vz/=Math.max(1,length);const speed=(keys.ShiftLeft||pad?.buttons?.[7]?.pressed?8:5.7)*dt,position=world.resolve(hero.group.position.x+vx*speed,hero.group.position.z+vz*speed,.52);hero.group.position.x=position.x;hero.group.position.z=position.z}
  const pressed=!!pad?.buttons?.[0]?.pressed;if(pressed&&!lastA)interact();lastA=pressed;hero.update(vx,vz,moving,time);
  const cancel=!!pad?.buttons?.[1]?.pressed;if(cancel&&!lastB)dialogue.hidden=true;lastB=cancel;
}
function frame(timeMs){requestAnimationFrame(frame);const dt=Math.min(.05,clock.getDelta()),time=timeMs*.001;input(dt,time);display.follow(hero.group.position,dt);nearby=world.nearest(hero.group.position.x,hero.group.position.z);const orbit=world.stations.find(station=>station.action==='orbit');if(roomGain&&orbit){const distance=Math.hypot(hero.group.position.x-orbit.x,hero.group.position.z-orbit.z),level=Math.max(0,1-distance/24);roomGain.gain.setTargetAtTime(.002+level*.023,soundContext.currentTime,.08);roomTone.frequency.setTargetAtTime(68+level*20,soundContext.currentTime,.08);if(roomPan)roomPan.pan.setTargetAtTime(Math.max(-.85,Math.min(.85,(orbit.x-hero.group.position.x)/16)),soundContext.currentTime,.08)}for(const station of world.stations){if(station.pad)station.pad.material.emissiveIntensity=(nearby?.id===station.id)?0.75:0.18}display.draw()}

fetch('/api/games').then(response=>response.json()).then(data=>{const games=data.games||[],wanted=Array.isArray(savedSetup.cabinetRoms)&&savedSetup.cabinetRoms.length?savedSetup.cabinetRoms:games.slice(0,8).map(game=>game.rom),selected=wanted.map(rom=>games.find(game=>game.rom===rom)).filter(Boolean);selected.forEach((game,index)=>world.addArcade(game,index))}).catch(()=>{});
window.NovaShellWorld={position:()=>({x:Number(hero.group.position.x.toFixed(2)),z:Number(hero.group.position.z.toFixed(2))})};
requestAnimationFrame(frame);
