const CACHE='homebase-v137';
const SHELL=[
  '/', '/index.html', '/offline.html', '/manifest.webmanifest', '/assets/icons/homebase-icon.svg', '/user-apps/wellness/reset-station/index.html', '/user-apps/wellness/reset-station/app.json', '/user-apps/wellness/reset-station/app.css', '/user-apps/wellness/reset-station/app.js',
  '/pages/arcade.html', '/pages/discover.html', '/pages/files.html', '/pages/apps.html', '/pages/source-connection.html',
  '/pages/settings.html', '/pages/github-setup.html', '/pages/readme-studio.html', '/user-apps/productivity/focus-deck/index.html', '/user-apps/productivity/focus-deck/app.json', '/user-apps/productivity/focus-deck/app.css', '/user-apps/productivity/focus-deck/app.js', '/user-apps/productivity/writer-desk/index.html', '/user-apps/productivity/writer-desk/app.json', '/user-apps/productivity/writer-desk/app.css', '/user-apps/productivity/writer-desk/app.js', '/user-apps/utilities/pantry-ledger/index.html', '/user-apps/utilities/pantry-ledger/app.json', '/user-apps/utilities/pantry-ledger/app.css', '/user-apps/utilities/pantry-ledger/app.js', '/user-apps/media/loop-lab/index.html', '/user-apps/media/loop-lab/app.json', '/user-apps/media/loop-lab/app.css', '/user-apps/media/loop-lab/app.js',
  '/pages/browse.html', '/pages/game-setup.html', '/pages/game-manager.html', '/pages/console.html', '/version.json', '/modules/radio-orbit/index.html', '/user-apps/games/quest-board/index.html', '/user-apps/games/quest-board/app.json', '/user-apps/games/novashell-world/index.html', '/user-apps/games/novashell-world/app.json', '/user-apps/games/novashell-world/world.css', '/user-apps/games/novashell-world/world3d.js', '/user-apps/games/novashell-world/vendor/three.module.js', '/user-apps/reference/pokedex-browser/index.html', '/user-apps/reference/pokedex-browser/app.json', '/user-apps/reference/pokedex-browser/app.css', '/user-apps/reference/pokedex-browser/app.js', '/modules/radio-orbit/style.css', '/modules/radio-orbit/embedded.css', '/modules/radio-orbit/colorful.css', '/modules/radio-orbit/classic-gray.css', '/modules/radio-orbit/orbit-controls.css', '/modules/radio-orbit/retro-visual-fix.css', '/modules/radio-orbit/orbit-contrast.css', '/modules/radio-orbit/orbit-contrast-plus.css', '/modules/radio-orbit/orbit-channel-rail.css', '/modules/radio-orbit/theme-inherit.css', '/modules/radio-orbit/app.js', '/assets/styles/discovery/browse.css', '/assets/scripts/discovery/browse.js',
  '/assets/styles/homebase/visual-deck.css', '/assets/styles/homebase/shell.css', '/assets/styles/homebase/first-run.css', '/assets/styles/homebase/first-run-shortcuts.css', '/assets/styles/homebase/command-palette.css',
  '/assets/styles/homebase/tiles.css', '/assets/styles/homebase/clock.css',
  '/assets/styles/homebase/gestures.css', '/assets/styles/homebase/indicators.css',
  '/assets/styles/homebase/system-insights.css', '/assets/styles/homebase/neofetch-ambient.css','/assets/styles/homebase/neofetch-cobalt.css','/assets/styles/homebase/neofetch-retro-readout.css','/assets/styles/homebase/relay-live-build.css','/assets/styles/homebase/project-board-interaction.css','/assets/styles/homebase/relay-free-routes.css','/assets/styles/homebase/window-layering.css','/assets/styles/homebase/about-overview.css','/modules/radio-orbit/theme-inherit-surfaces.css','/assets/styles/shared/retro-window-standard.css', '/assets/styles/homebase/scroll-motion.css',
  '/assets/styles/homebase/themes.css', '/assets/styles/homebase/liquid-modern.css', '/assets/styles/homebase/mini-player.css',
  '/assets/styles/homebase/tile-layout.css', '/assets/styles/homebase/glass.css',
  '/assets/styles/homebase/header-actions.css', '/assets/styles/homebase/orbit-performance.css',
  '/assets/styles/arcade/archive.css', '/assets/styles/arcade/emulator-performance.css',
  '/assets/styles/arcade/game-details.css', '/assets/styles/arcade/multiplayer.css',
  '/assets/styles/arcade/performance.css', '/assets/styles/discovery/discover.css',
  '/assets/styles/discovery/discover-gallery.css', '/assets/styles/discovery/discover-offline-art.css', '/assets/styles/files/files.css',
  '/assets/styles/files/dialog.css', '/assets/styles/files/files-mobile-actions.css','/assets/styles/files/gallery.css', '/assets/scripts/files/files-rename.js', '/assets/scripts/files/files-trash-confirm.js', '/assets/scripts/files/files-copy-paste.js', '/assets/scripts/files/files-inapp-actions.js', '/assets/styles/apps/catalog.css',
  '/assets/styles/apps/apps-install-modal.css', '/assets/styles/settings/settings.css', '/assets/styles/settings/settings-desktop-theme-sync.css', '/assets/styles/settings/settings-device-center.css',
  '/assets/styles/settings/settings-dialog.css', '/assets/styles/shared/modal-global.css',
  '/assets/styles/shared/ultra-retro.css', '/assets/styles/shared/back-button-spacing.css', '/assets/styles/homebase/fake-virus-lab.css', '/assets/styles/apps/apps-icon-alignment.css', '/assets/scripts/homebase/deck.js', '/assets/scripts/homebase/command-palette.js', '/assets/scripts/homebase/first-run.js', '/assets/scripts/homebase/first-run-shortcuts.js', '/assets/scripts/shared/about-novashell.js',
  '/assets/scripts/homebase/deck-gestures.js', '/assets/scripts/homebase/gyro3d.js', '/assets/scripts/homebase/console.js', '/assets/scripts/homebase/relay-brain-panel.js','/assets/scripts/homebase/relay-live-build.js','/assets/scripts/homebase/project-board-interaction.js','/assets/scripts/homebase/relay-free-routes.js','/assets/scripts/homebase/window-layering.js','/assets/scripts/shared/about-novashell.js','/assets/scripts/shared/about-overview.js', '/assets/scripts/homebase/relay-brain-browser.js', '/assets/scripts/homebase/relay-workshop-components.js', '/assets/scripts/homebase/relay-provider-config.js', '/assets/scripts/homebase/relay-workspace.js', '/assets/scripts/homebase/utility-project-board.js', '/assets/scripts/homebase/update-check.js', '/assets/styles/homebase/console.css', '/assets/styles/homebase/relay-composer-flow.css', '/assets/styles/homebase/relay-brain-deck.css', '/assets/styles/homebase/relay-brain-browser.css', '/assets/styles/homebase/relay-brain-graph.css', '/assets/styles/homebase/relay-contrast-guard.css', '/assets/styles/homebase/relay-provider-config.css', '/assets/styles/homebase/relay-codex-runner.css',
  '/assets/scripts/homebase/clock.js', '/assets/scripts/homebase/system-insights.js', '/assets/scripts/homebase/neofetch-ambient.js', '/assets/scripts/homebase/utility-workspace-manifest.js', '/assets/scripts/homebase/utility-live-snapshot.js', '/assets/scripts/homebase/utility-app-shelf.js', '/assets/styles/homebase/utility-app-shelf.css',
  '/assets/scripts/homebase/scroll-motion.js', '/assets/scripts/arcade/game-controls.js', '/assets/scripts/arcade/world-cabinet-handoff.js',
  '/assets/scripts/arcade/game-capture.js', '/assets/scripts/arcade/game-details.js', '/assets/scripts/arcade/launch-readiness.js',
  '/assets/scripts/arcade/library-extras.js', '/assets/scripts/arcade/performance.js',
  '/assets/scripts/arcade/multiplayer.js', '/assets/scripts/arcade/browser-saves.js',
  '/assets/scripts/discovery/discover.js', '/assets/scripts/discovery/discover-resilience.js', '/assets/scripts/homebase/fake-virus-lab.js', '/assets/scripts/files/files.js','/assets/scripts/files/files-gallery.js',
  '/assets/scripts/apps/apps-enhance.js', '/assets/scripts/apps/apps-install-modal.js',
  '/assets/scripts/apps/install-jobs.js',
  '/assets/scripts/settings/settings.js', '/assets/scripts/settings/settings-restore.js', '/assets/scripts/settings/settings-device-center.js',
  '/assets/scripts/settings/settings-options.js', '/assets/scripts/shared/theme-sync.js',
  '/assets/scripts/shared/github-status.js',
  '/assets/styles/homebase/relay-composer-flow.css', '/assets/styles/homebase/relay-keyring.css',
  '/assets/scripts/homebase/relay-keyring.js'
];
SHELL.push('/user-apps/productivity/focus-deck/rounds.css','/user-apps/productivity/focus-deck/rounds.js','/user-apps/utilities/rail-finder/index.html','/user-apps/utilities/rail-finder/app.json','/user-apps/utilities/rail-finder/app.css','/user-apps/utilities/rail-finder/app.js','/assets/styles/homebase/neofetch-placement.css','/user-apps/games/novashell-world/engine/pixel-renderer.js','/user-apps/games/novashell-world/engine/pixel-actor.js','/user-apps/games/novashell-world/engine/world.js','/user-apps/games/novashell-world/content/building.js');
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;event.respondWith(fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response}).catch(async()=>{const exact=await caches.match(event.request),pathFallback=await caches.match(event.request,{ignoreSearch:true});return exact||pathFallback||(event.request.mode==='navigate'?caches.match('/offline.html'):Response.error())}))});
