(()=>{
  const URL='https://data.cityofchicago.org/resource/8pix-ypme.json?$limit=1200',KEY='novashell-rail-stations-v1',$=s=>document.querySelector(s),host=$('#stations');
  const routes={red:['Red','#c60c30'],blue:['Blue','#00a1de'],g:['Green','#009b3a'],brn:['Brown','#8b5a2b'],o:['Orange','#f57c00'],p:['Purple','#7b4ab4'],pnk:['Pink','#d96d9e'],y:['Yellow','#b89b00']};let stations=[],locationPoint=null;
  function clean(value){const node=document.createElement('span');node.textContent=String(value||'');return node.innerHTML}function distance(a,b,c,d){const r=3959,toRad=x=>x*Math.PI/180,x=toRad(c-a),y=toRad(d-b),q=Math.sin(x/2)**2+Math.cos(toRad(a))*Math.cos(toRad(c))*Math.sin(y/2)**2;return 2*r*Math.asin(Math.sqrt(q))}
  function normalize(rows){const by=new Map;for(const row of rows){if(!row.map_id)continue;const found=by.get(row.map_id)||{id:row.map_id,name:row.station_name,description:row.station_descriptive_name,ada:Boolean(row.ada),lat:Number(row.location?.latitude),lon:Number(row.location?.longitude),lines:[]};for(const key of Object.keys(routes))if(row[key]===true&&!found.lines.includes(key))found.lines.push(key);by.set(row.map_id,found)}return [...by.values()].sort((a,b)=>a.name.localeCompare(b.name))}
  function render(){const term=$('#search').value.trim().toLowerCase(),line=$('#line').value,ada=$('#ada').checked;let shown=stations.filter(s=>(!term||`${s.name} ${s.description}`.toLowerCase().includes(term))&&(!line||s.lines.includes(line))&&(!ada||s.ada));if(locationPoint)shown.sort((a,b)=>distance(locationPoint[0],locationPoint[1],a.lat,a.lon)-distance(locationPoint[0],locationPoint[1],b.lat,b.lon));host.innerHTML=shown.length?shown.map(s=>`<article class="station"><h2>${clean(s.name)}</h2><p>${clean(s.description)}</p><div class="lines">${s.lines.map(key=>`<span class="line" style="color:${routes[key][1]}">${routes[key][0]}</span>`).join('')}</div><footer><span>${s.ada?'ACCESSIBLE':'ACCESS VARIES'}</span><span>${locationPoint?distance(locationPoint[0],locationPoint[1],s.lat,s.lon).toFixed(1)+' mi away':'MAP ID '+s.id}</span></footer></article>`).join(''):'<div class="empty">No stations match those filters.</div>';$('#status').textContent=`${shown.length} of ${stations.length} stations · ${locationPoint?'sorted nearest first':'alphabetical'}`}
  async function load(){let source='live';try{const rows=await fetch(URL).then(r=>{if(!r.ok)throw Error();return r.json()});stations=normalize(rows);localStorage.setItem(KEY,JSON.stringify({saved:Date.now(),stations}))}catch{let cached=null;try{cached=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}stations=cached?.stations||[];source=stations.length?'cached':'unavailable'}for(const [key,[name]] of Object.entries(routes))$('#line').insertAdjacentHTML('beforeend',`<option value="${key}">${name} Line</option>`);if(!stations.length){$('#status').textContent='Station directory unavailable and no local cache exists.';return}render();$('#status').textContent+=source==='cached'?' · cached copy':' · official directory refreshed'}
  ['#search','#line','#ada'].forEach(selector=>$(selector).addEventListener(selector==='#search'?'input':'change',render));$('#nearest').onclick=()=>{if(!navigator.geolocation){$('#status').textContent='Location is not available in this browser.';return}$('#status').textContent='Requesting this device location…';navigator.geolocation.getCurrentPosition(position=>{locationPoint=[position.coords.latitude,position.coords.longitude];render()},()=>{$('#status').textContent='Location permission was not granted. The alphabetical directory still works.'},{timeout:8000,maximumAge:300000})};load();
})();
