(()=>{
  const KEY='novashell-reset-station-v2',$=selector=>document.querySelector(selector),today=new Date().toISOString().slice(0,10),orb=$('#orb');
  const methods=[
    {id:'coherent-55',name:'Coherent · 5·5',pattern:'5–5',info:'A simple even rhythm: five seconds in, five seconds out.',phases:[['inhale',5],['exhale',5]]},
    {id:'box-4444',name:'Box · 4·4·4·4',pattern:'4–4–4–4',info:'Equal inhale, hold, exhale, and hold phases.',phases:[['inhale',4],['hold',4],['exhale',4],['hold',4]]},
    {id:'box-5555',name:'Slow box · 5·5·5·5',pattern:'5–5–5–5',info:'A slower equal-count box pattern.',phases:[['inhale',5],['hold',5],['exhale',5],['hold',5]]},
    {id:'relax-478',name:'Long exhale · 4·7·8',pattern:'4–7–8',info:'Four seconds in, seven holding, and a slow eight-second exhale.',phases:[['inhale',4],['hold',7],['exhale',8]]},
    {id:'extended-4488',name:'Extended · 4·4·8·8',pattern:'4–4–8–8',info:'A longer exhale and empty hold; use only if it remains comfortable.',phases:[['inhale',4],['hold',4],['exhale',8],['hold',8]]},
    {id:'triangle-444',name:'Triangle · 4·4·4',pattern:'4–4–4',info:'A beginner-friendly three-phase pattern.',phases:[['inhale',4],['hold',4],['exhale',4]]},
    {id:'belly-46',name:'Belly · 4·6',pattern:'4–6',info:'A gentle four-second inhale followed by a longer six-second exhale.',phases:[['inhale',4],['exhale',6]]}
  ];
  let stored;try{stored=JSON.parse(localStorage.getItem(KEY))}catch{}const settings={method:stored?.method||'coherent-55',waterGoal:Number(stored?.waterGoal)||8,breakGoal:Number(stored?.breakGoal)||3,chime:!!stored?.chime};
  let data=stored?.date===today?stored:{date:today,cups:0,checks:[],breaks:[],guided:false,history:[],...settings};data.breaks=Array.isArray(data.breaks)?data.breaks:[];data.history=Array.isArray(data.history)?data.history:[];
  let mainTimer=0,end=0,cycleStart=0,running=false,guidedRun=false,lastPhase=-1,audioContext=null;
  const method=()=>methods.find(item=>item.id===data.method)||methods[0],score=()=>Math.round(Math.min(1,data.cups/data.waterGoal)*40+Math.min(1,data.breaks.length/data.breakGoal)*40+(data.guided?20:0));
  const save=(record=true)=>{if(record){const value=score(),last=data.history.at(-1);if(!last||last.value!==value){data.history.push({time:Date.now(),value});data.history=data.history.slice(-120)}}localStorage.setItem(KEY,JSON.stringify(data))};
  function chime(){if(!data.chime)return;try{const Context=window.AudioContext||window.webkitAudioContext;audioContext ||= new Context();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.frequency.value=520;gain.gain.setValueAtTime(.035,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.12);oscillator.connect(gain).connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+.13)}catch{}}
  function drawHistory(){const canvas=$('#history'),ctx=canvas.getContext('2d'),box=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(box.width)),h=Math.max(1,Math.round(box.height));if(canvas.width!==w*ratio||canvas.height!==h*ratio){canvas.width=w*ratio;canvas.height=h*ratio}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);const retro=document.documentElement.dataset.theme==='ultra-retro';ctx.strokeStyle=retro?'#777':'#ffffff18';ctx.lineWidth=1;for(const value of[25,50,75]){const y=h-(value/100)*(h-20)-10;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const points=data.history;if(!points.length)return;ctx.strokeStyle=retro?'#000080':'#79ddca';ctx.lineWidth=2;ctx.beginPath();points.forEach((point,index)=>{const x=points.length===1?w-8:index/(points.length-1)*(w-16)+8,y=h-(point.value/100)*(h-20)-10;index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();const last=points.at(-1),x=w-8,y=h-(last.value/100)*(h-20)-10;ctx.fillStyle=ctx.strokeStyle;ctx.fillRect(x-3,y-3,6,6)}
  function render(){
    $('#cups').textContent=data.cups;$('#score').textContent=score();$('#hydration-stat').textContent=`${data.cups} / ${data.waterGoal}`;$('#break-stat').textContent=`${data.breaks.length} / ${data.breakGoal}`;$('#water-meter').style.width=Math.min(100,data.cups/data.waterGoal*100)+'%';
    $('#water-pace').textContent=data.cups>=data.waterGoal?'Daily goal reached.':`${Math.max(0,data.waterGoal-data.cups)} glass${data.waterGoal-data.cups===1?'':'es'} remaining in your chosen goal.`;
    const last=data.breaks.at(-1),elapsed=last?Math.max(0,(Date.now()-last)/60000):null,progress=elapsed==null?0:Math.min(100,elapsed/90*100);$('#break-meter').style.width=progress+'%';$('#break-meter').className=progress>=100?'overdue':progress>=80?'soon':'';$('#since-break').textContent=elapsed==null?'No break logged yet':elapsed<1?'Break logged just now':elapsed<90?`${Math.floor(elapsed)} min since last break`:`Reset overdue by ${Math.floor(elapsed-90)} min`;
    $('#last-reset').textContent=data.guided?'DONE':last?new Date(last).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'—';$('#break-dots').replaceChildren(...Array.from({length:Math.max(data.breakGoal,data.breaks.length)},(_,index)=>{const dot=document.createElement('i');dot.classList.toggle('done',index<data.breaks.length);return dot}));
    document.querySelectorAll('#check-list input').forEach(box=>box.checked=data.checks.includes(box.value));$('#history-label').textContent=data.history.length?`${data.history.length} change${data.history.length===1?'':'s'} today`:'No entries yet';drawHistory();
  }
  function renderMethod(){const selected=method();$('#method-info').textContent=`${selected.info} Pattern: ${selected.pattern}.`;$('#phase-strip').replaceChildren(...selected.phases.map(([name,seconds])=>{const span=document.createElement('span');span.dataset.phase=name;span.textContent=`${name} ${seconds}s`;return span}))}
  function setPhase(index,remaining){const selected=method(),[name]=selected.phases[index];orb.className=`orb ${name}`;$('#phase').textContent=name.toUpperCase();$('#phase-count').textContent=Math.ceil(remaining);document.querySelectorAll('#phase-strip span').forEach((span,position)=>span.classList.toggle('active',position===index));if(index!==lastPhase){lastPhase=index;chime()}}
  function tick(){const left=Math.max(0,end-Date.now()),seconds=Math.ceil(left/1000);$('#time').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;if(!left){stop(true);return}const selected=method(),cycle=selected.phases.reduce((sum,[,duration])=>sum+duration,0),within=(Date.now()-cycleStart)/1000%cycle;let cursor=0,index=0;for(let position=0;position<selected.phases.length;position++){const duration=selected.phases[position][1];if(within<cursor+duration){index=position;setPhase(index,cursor+duration-within);break}cursor+=duration}}
  function stop(done=false){const completedGuided=guidedRun;clearInterval(mainTimer);mainTimer=0;running=false;guidedRun=false;orb.className='orb';$('#phase').textContent=done?'DONE':'READY';$('#phase-count').textContent='—';$('#stop').disabled=true;document.querySelectorAll('[data-min],#guided,#method').forEach(node=>node.disabled=false);document.querySelectorAll('#phase-strip span').forEach(span=>span.classList.remove('active'));if(done&&completedGuided){data.guided=true;data.breaks.push(Date.now());save();render()}lastPhase=-1}
  function start(minutes,guided=false){stop();running=true;guidedRun=guided;end=Date.now()+minutes*60000;cycleStart=Date.now();$('#time').textContent=`${String(minutes).padStart(2,'0')}:00`;$('#stop').disabled=false;document.querySelectorAll('[data-min],#guided,#method').forEach(node=>node.disabled=true);mainTimer=setInterval(tick,100);tick()}
  methods.forEach(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.name;$('#method').append(option)});$('#method').value=data.method;for(let value=4;value<=16;value++){const option=document.createElement('option');option.value=value;option.textContent=value+' glasses';$('#water-goal').append(option)}$('#water-goal').value=data.waterGoal;for(let value=1;value<=8;value++){const option=document.createElement('option');option.value=value;option.textContent=value+' breaks';$('#break-goal').append(option)}$('#break-goal').value=data.breakGoal;$('#chime').checked=data.chime;
  $('#method').onchange=()=>{data.method=$('#method').value;save(false);renderMethod()};$('#water-goal').onchange=()=>{data.waterGoal=Number($('#water-goal').value);save();render()};$('#break-goal').onchange=()=>{data.breakGoal=Number($('#break-goal').value);save();render()};$('#chime').onchange=()=>{data.chime=$('#chime').checked;save(false)};
  $('#less').onclick=()=>{data.cups=Math.max(0,data.cups-1);save();render()};$('#more').onclick=()=>{data.cups++;save();render()};$('#log-break').onclick=()=>{data.breaks.push(Date.now());save();render()};$('#guided').onclick=()=>start(5,true);document.querySelectorAll('[data-min]').forEach(button=>button.onclick=()=>start(Number(button.dataset.min),false));$('#stop').onclick=()=>stop(false);
  document.querySelectorAll('#check-list input').forEach(box=>box.onchange=()=>{data.checks=box.checked?[...new Set([...data.checks,box.value])]:data.checks.filter(value=>value!==box.value);save();render()});
  addEventListener('resize',drawHistory);setInterval(render,30000);save(false);renderMethod();render();
})();
