(()=>{
  const KEY='novashell-pose-lab-v1',$=s=>document.querySelector(s),canvas=$('#rig'),ctx=canvas.getContext('2d');
  const base={head:[.5,.17],neck:[.5,.28],leftShoulder:[.39,.32],rightShoulder:[.61,.32],leftElbow:[.31,.45],rightElbow:[.69,.45],leftHand:[.27,.59],rightHand:[.73,.59],hips:[.5,.55],leftKnee:[.43,.72],rightKnee:[.57,.72],leftFoot:[.40,.91],rightFoot:[.60,.91]};
  const bones=[['head','neck'],['neck','leftShoulder'],['neck','rightShoulder'],['neck','hips'],['leftShoulder','leftElbow'],['leftElbow','leftHand'],['rightShoulder','rightElbow'],['rightElbow','rightHand'],['hips','leftKnee'],['leftKnee','leftFoot'],['hips','rightKnee'],['rightKnee','rightFoot']];
  let joints=structuredClone(base),poses=read(),selected=[],drag='',animation=0,removeId='';
  function read(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return []}}function persist(){localStorage.setItem(KEY,JSON.stringify(poses))}
  function clean(value){const node=document.createElement('span');node.textContent=String(value);return node.innerHTML}
  function xy(name){return[joints[name][0]*canvas.width,joints[name][1]*canvas.height]}
  function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#8edfec';ctx.lineWidth=12;ctx.lineCap='round';for(const [a,b] of bones){ctx.beginPath();ctx.moveTo(...xy(a));ctx.lineTo(...xy(b));ctx.stroke()}ctx.beginPath();ctx.fillStyle='#d9f6f9';const [hx,hy]=xy('head');ctx.arc(hx,hy,50,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#173b48';ctx.stroke();for(const [name] of Object.entries(joints)){const [x,y]=xy(name);ctx.beginPath();ctx.fillStyle=name===drag?'#ffe08b':'#f4fbfc';ctx.arc(x,y,15,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#173b48';ctx.lineWidth=4;ctx.stroke()}}
  function render(){$('#count').textContent=String(poses.length);$('#poses').innerHTML=poses.length?poses.map(pose=>`<article class="pose"><input type="checkbox" data-select="${pose.id}" ${selected.includes(pose.id)?'checked':''} aria-label="Select ${clean(pose.name)}"><button data-load="${pose.id}">${clean(pose.name)}</button><button data-delete="${pose.id}">×</button></article>`).join(''):'<p class="empty">No poses saved yet.</p>';$('#preview').disabled=selected.length!==2}
  function point(event){const rect=canvas.getBoundingClientRect();return[(event.clientX-rect.left)/rect.width,(event.clientY-rect.top)/rect.height]}
  canvas.onpointerdown=event=>{const [px,py]=point(event);drag=Object.keys(joints).sort((a,b)=>Math.hypot(joints[a][0]-px,joints[a][1]-py)-Math.hypot(joints[b][0]-px,joints[b][1]-py))[0];canvas.setPointerCapture(event.pointerId);draw()};canvas.onpointermove=event=>{if(!drag)return;const [x,y]=point(event);joints[drag]=[Math.max(.03,Math.min(.97,x)),Math.max(.03,Math.min(.97,y))];draw()};canvas.onpointerup=()=>{drag='';draw()};
  $('#save').onclick=()=>{const name=$('#name').value.trim()||`Pose ${poses.length+1}`;poses.unshift({id:crypto.randomUUID(),name,joints:structuredClone(joints),created:Date.now()});persist();$('#name').value='';render()};$('#reset').onclick=()=>{joints=structuredClone(base);draw()};
  $('#poses').onclick=event=>{const load=event.target.dataset.load,del=event.target.dataset.delete,select=event.target.dataset.select;if(load){const pose=poses.find(item=>item.id===load);joints=structuredClone(pose.joints);draw()}if(del){removeId=del;$('#remove').showModal()}if(select){selected=event.target.checked?[...selected,select]:selected.filter(id=>id!==select);selected=selected.slice(-2);render()}};
  const remove=$('#remove');remove.onclick=event=>{if(event.target===remove)remove.close()};remove.querySelector('div button').onclick=()=>remove.close();$('#keep').onclick=()=>remove.close();$('#confirm').onclick=()=>{poses=poses.filter(pose=>pose.id!==removeId);selected=selected.filter(id=>id!==removeId);persist();remove.close();render()};
  $('#preview').onclick=()=>{const a=poses.find(p=>p.id===selected[0]),b=poses.find(p=>p.id===selected[1]);if(!a||!b)return;cancelAnimationFrame(animation);const start=performance.now(),run=now=>{const raw=((now-start)%2400)/2400,t=raw<.5?raw*2:(1-raw)*2;for(const name of Object.keys(base))joints[name]=[a.joints[name][0]+(b.joints[name][0]-a.joints[name][0])*t,a.joints[name][1]+(b.joints[name][1]-a.joints[name][1])*t];draw();animation=requestAnimationFrame(run)};animation=requestAnimationFrame(run);$('#stop').disabled=false};$('#stop').onclick=()=>{cancelAnimationFrame(animation);animation=0;$('#stop').disabled=true};
  $('#export').onclick=()=>{const blob=new Blob([JSON.stringify({format:'novashell-pose-set-v1',poses},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='novashell-poses.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};draw();render();
})();
