(() => {
  const $=selector=>document.querySelector(selector),CACHE='novashell-weather-report-v2';
  const codes={0:['☀','Clear sky'],1:['◌','Mostly clear'],2:['☁','Partly cloudy'],3:['☁','Overcast'],45:['≋','Fog'],48:['≋','Rime fog'],51:['☂','Light drizzle'],53:['☂','Drizzle'],55:['☂','Heavy drizzle'],56:['☂','Freezing drizzle'],57:['☂','Heavy freezing drizzle'],61:['☂','Light rain'],63:['☂','Rain'],65:['☂','Heavy rain'],66:['☂','Freezing rain'],67:['☂','Heavy freezing rain'],71:['❄','Light snow'],73:['❄','Snow'],75:['❄','Heavy snow'],77:['·','Snow grains'],80:['☂','Rain showers'],81:['☂','Rain showers'],82:['☂','Heavy showers'],85:['❄','Snow showers'],86:['❄','Heavy snow showers'],95:['ϟ','Thunderstorm'],96:['ϟ','Thunderstorm with hail'],99:['ϟ','Severe thunderstorm']};
  const condition=value=>codes[value]||['◌','Changing skies'],round=value=>Number.isFinite(Number(value))?Math.round(Number(value)):'—',fixed=value=>Number.isFinite(Number(value))?Number(value).toFixed(2):'—';
  const compass=degrees=>['N','NE','E','SE','S','SW','W','NW'][Math.round((Number(degrees)||0)/45)%8];
  const clock=value=>value?new Date(value).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'—';
  const day=value=>new Date(value+'T12:00').toLocaleDateString([],{weekday:'short'});
  async function json(url){const response=await fetch(url);const data=await response.json();if(!response.ok||data.error)throw Error(data.reason||data.error||'Weather source unavailable');return data}
  function aqiLabel(value){const n=Number(value);if(!Number.isFinite(n))return['Unavailable','none'];if(n<=50)return['Good','good'];if(n<=100)return['Moderate','moderate'];if(n<=150)return['Sensitive groups','sensitive'];if(n<=200)return['Unhealthy','unhealthy'];return['Very unhealthy','hazard']}
  function setLoading(on){document.body.classList.toggle('loading',on);$('#search').querySelectorAll('button,input').forEach(node=>node.disabled=on)}
  async function resolvePlace(query){const geo=await json('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(query)+'&count=1&language=en&format=json'),hit=geo.results?.[0];if(!hit)throw Error('No matching place. Try a nearby city, state, or country.');return hit}
  async function fetchReport(hit){
    const point=`latitude=${encodeURIComponent(hit.latitude)}&longitude=${encodeURIComponent(hit.longitude)}`;
    const forecastUrl='https://api.open-meteo.com/v1/forecast?'+point+'&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m,wind_gusts_10m,wind_direction_10m,relative_humidity_2m,precipitation,cloud_cover,is_day,surface_pressure&hourly=temperature_2m,apparent_temperature,precipitation_probability,weather_code,wind_speed_10m,relative_humidity_2m,visibility&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,uv_index_max,sunrise,sunset,wind_speed_10m_max&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&forecast_days=7&timezone=auto';
    const airUrl='https://air-quality-api.open-meteo.com/v1/air-quality?'+point+'&current=us_aqi,pm2_5,pm10,ozone,uv_index&timezone=auto';
    const [weather,air]=await Promise.all([json(forecastUrl),json(airUrl).catch(()=>({current:{}}))]);return{hit,weather,air,saved:Date.now()};
  }
  function renderHourly(weather){const values=weather.hourly||{},current=String(weather.current?.time||'').slice(0,13),start=Math.max(0,values.time?.findIndex(time=>String(time).slice(0,13)>=current)??0);$('#hourly').innerHTML=(values.time||[]).slice(start,start+12).map((time,offset)=>{const i=start+offset,look=condition(values.weather_code?.[i]);return `<article class="hour"><b>${clock(time)}</b><span>${look[0]}</span><strong>${round(values.temperature_2m?.[i])}°</strong><small>${round(values.precipitation_probability?.[i])}% rain · ${round(values.wind_speed_10m?.[i])} mph</small></article>`}).join('')||'<p>Hourly data is unavailable.</p>'}
  function renderDaily(weather){const values=weather.daily||{};$('#forecast').innerHTML=(values.time||[]).map((time,i)=>{const look=condition(values.weather_code?.[i]);return `<article class="day"><b>${day(time)}</b><span>${look[0]}</span><strong>${round(values.temperature_2m_max?.[i])}° / ${round(values.temperature_2m_min?.[i])}°</strong><small>${round(values.precipitation_probability_max?.[i])}% rain · ${round(values.wind_speed_10m_max?.[i])} mph</small></article>`}).join('')||'<p>Daily data is unavailable.</p>'}
  function render(report,cached=false){
    const {hit,weather,air}=report,current=weather.current||{},look=condition(current.weather_code),place=[hit.name,hit.admin1,hit.country_code].filter(Boolean).join(', '),aq=air.current||{},[quality,qualityClass]=aqiLabel(aq.us_aqi);
    $('#name').textContent=place;$('#location-name').textContent=place;$('#location-detail').textContent=[hit.country,hit.admin1].filter((value,index,array)=>value&&array.indexOf(value)===index).join(' · ')||'Location details unavailable';$('#glyph').textContent=look[0];$('#condition-code').textContent=look[1].toUpperCase();$('#summary').textContent=`${look[1]} · feels like ${round(current.apparent_temperature)}°`;$('#details').textContent=`Wind ${round(current.wind_speed_10m)} mph ${compass(current.wind_direction_10m)} · clouds ${round(current.cloud_cover)}%`;$('#temp').textContent=round(current.temperature_2m)+'°';$('#updated').textContent=(cached?'CACHED REPORT · ':'UPDATED ')+clock(current.time||report.saved);
    $('#feels').textContent=round(current.apparent_temperature)+'°';$('#humidity').textContent=round(current.relative_humidity_2m)+'%';$('#wind').textContent=round(current.wind_speed_10m)+' mph';$('#wind-direction').textContent=compass(current.wind_direction_10m)+' · '+round(current.wind_direction_10m)+'°';$('#gust').textContent=round(current.wind_gusts_10m)+' mph';$('#rain').textContent=fixed(current.precipitation)+' in';$('#cloud').textContent=round(current.cloud_cover)+'%';$('#pressure').textContent=round(current.surface_pressure)+' hPa';$('#sun').textContent=current.is_day?'DAY':'NIGHT';
    $('#timezone').textContent=weather.timezone_abbreviation||weather.timezone||'—';$('#elevation').textContent=round(weather.elevation)+' m';$('#coordinates').textContent=`${Number(hit.latitude).toFixed(2)}, ${Number(hit.longitude).toFixed(2)}`;
    $('#aqi').textContent=round(aq.us_aqi);$('#pm25').textContent=round(aq.pm2_5)+' μg/m³';$('#pm10').textContent=round(aq.pm10)+' μg/m³';$('#ozone').textContent=round(aq.ozone)+' μg/m³';$('#aqi-badge').textContent=quality;$('#aqi-badge').dataset.level=qualityClass;
    const daily=weather.daily||{},uv=Number(daily.uv_index_max?.[0]);$('#sunrise').textContent=clock(daily.sunrise?.[0]);$('#sunset').textContent=clock(daily.sunset?.[0]);$('#uv-label').textContent=Number.isFinite(uv)?`UV ${uv.toFixed(1)}`:'UV unavailable';$('#uv').textContent=Number.isFinite(uv)?`Forecast maximum UV index: ${uv.toFixed(1)}. Use local guidance appropriate to your plans.`:'UV forecast unavailable.';
    renderHourly(weather);renderDaily(weather);$('#report').hidden=false;$('#signal').textContent=cached?'CACHED LOCAL REPORT':'LIVE FORECAST READY';$('#status').textContent=cached?'Network unavailable · showing the last report saved on this device.':'Live forecast received · no account or personal profile required.';startSky(Number(current.weather_code)||0,!!current.is_day);
  }
  async function load(query){if(!query?.trim()){ $('#status').textContent='Enter a city, town, or postal area first.';return}setLoading(true);$('#status').textContent='Tuning forecast for '+query.trim()+'…';try{const report=await fetchReport(await resolvePlace(query.trim()));localStorage.setItem(CACHE,JSON.stringify(report));render(report)}catch(error){let cached;try{cached=JSON.parse(localStorage.getItem(CACHE)||'null')}catch{}if(cached)render(cached,true);else{$('#status').textContent=error.message;$('#signal').textContent='SIGNAL UNAVAILABLE'}}finally{setLoading(false)}}
  $('#search').onsubmit=event=>{event.preventDefault();load($('#place').value)};
  $('#locate').onclick=()=>{if(!navigator.geolocation){$('#status').textContent='Location is not available in this browser.';return}$('#status').textContent='Waiting for browser location permission…';navigator.geolocation.getCurrentPosition(async position=>{setLoading(true);try{const hit={name:'Current location',latitude:position.coords.latitude,longitude:position.coords.longitude,country:''},report=await fetchReport(hit);localStorage.setItem(CACHE,JSON.stringify(report));render(report)}catch(error){$('#status').textContent=error.message}finally{setLoading(false)}},()=>$('#status').textContent='Location permission was not granted. Search by place name instead.',{timeout:9000,maximumAge:300000})};
  let skyFrame=0,skyCode=0,skyDay=true,lastSky=0;
  function startSky(code,isDay){skyCode=code;skyDay=isDay;if(!skyFrame)skyFrame=requestAnimationFrame(drawSky)}
  function drawSky(time){skyFrame=requestAnimationFrame(drawSky);if(document.hidden||time-lastSky<100)return;lastSky=time;const canvas=$('#weather-sky'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,retro=document.documentElement.dataset.theme==='ultra-retro',rain=(skyCode>=51&&skyCode<=67)||(skyCode>=80&&skyCode<=82)||skyCode>=95,snow=(skyCode>=71&&skyCode<=77)||(skyCode>=85&&skyCode<=86),cloudy=[2,3,45,48].includes(skyCode)||rain||snow,t=time*.001;ctx.imageSmoothingEnabled=false;ctx.fillStyle=retro?'#628ca2':skyDay?'#164c67':'#0a1533';ctx.fillRect(0,0,w,h);ctx.fillStyle=retro?'#ddd':skyDay?'#f4d278':'#d8e4ef';ctx.fillRect(145,10,skyDay?13:10,skyDay?13:10);if(cloudy){ctx.fillStyle=retro?'#b7b7b7':'#9db1b7';for(let cloud=0;cloud<4;cloud++){const x=((cloud*59+t*(3+cloud))%(w+40))-30,y=12+cloud*12;ctx.fillRect(x,y,28,7);ctx.fillRect(x+7,y-5,13,5)}}if(rain||snow){ctx.fillStyle=retro?'#000080':snow?'#e9fbff':'#72c8df';for(let i=0;i<34;i++){const x=(i*37+t*(rain?28:8))%w,y=(i*19+t*(rain?45:13))%h;ctx.fillRect(x,y,rain?1:2,rain?5:2)}}if(skyCode>=95&&Math.floor(t)%7===0){ctx.fillStyle=retro?'#fff':'#f7e99d';ctx.fillRect(96,15,2,18);ctx.fillRect(92,31,6,2);ctx.fillRect(92,31,2,13)}}
  const observer=new MutationObserver(()=>{lastSky=0});observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
  const requestedPlace=new URLSearchParams(location.search).get('place');
  try{const cached=JSON.parse(localStorage.getItem(CACHE)||'null');if(cached&&!requestedPlace)render(cached,true)}catch{}
  if(requestedPlace){$('#place').value=requestedPlace;load(requestedPlace)}else if($('#place').value.trim())load($('#place').value);
})();
